export const MOCK_DATA_MENU = [
  {
    category: 'Entrada',
    name: 'Bruschetta',
    description:
      'Pão italiano torrado coberto com tomate fresco, manjericão e azeite de oliva.',
    origin: 'Italiana',
    price: 12.5,
    id: '34f5e4f4-3fc9-472f-8097-5c5a3ded0581',
  },
  {
    category: 'Entrada',
    name: 'Salada Caprese',
    description:
      'Salada fresca de tomate, mussarela de búfala, manjericão e azeite balsâmico.',
    origin: 'Italiana',
    price: 15,
    id: 'f631bcbd-929d-4bed-97cd-75bf661aee90',
  },
  {
    category: 'Entrada',
    name: 'Carpaccio de Carne',
    description:
      'Fatias finas de carne crua temperadas com azeite, limão e parmesão.',
    origin: 'Italiana',
    price: 18,
    id: '603196f9-28c3-45c3-99cd-5b5c6e2e0338',
  },
  {
    category: 'Entrada',
    name: 'Arancini',
    description: 'Bolinhos de arroz recheados com queijo, empanados e fritos.',
    origin: 'Italiana',
    price: 14,
    id: '0fe20249-fb57-4e86-a341-09414d6449ff',
  },
  {
    category: 'Entrada',
    name: 'Antipasto',
    description:
      'Seleção de queijos, embutidos, azeitonas e vegetais marinados.',
    origin: 'Italiana',
    price: 20,
    id: '47af44e3-e080-4fea-aef9-d8b60540096e',
  },
  {
    category: 'Prato Principal',
    name: 'Filé Mignon ao Molho Madeira',
    description:
      'Filé mignon suculento acompanhado de molho madeira e batatas gratinadas.',
    origin: 'Portuguesa',
    price: 35,
    id: '5b3515bd-d366-4aa4-b414-d976f301c9fd',
  },
  {
    category: 'Prato Principal',
    name: 'Bacalhau à Brás',
    description: 'Desfiado de bacalhau com batatas fritas, ovos e azeitonas.',
    origin: 'Portuguesa',
    price: 32,
    id: 'fafc40de-9e37-45d1-a7a9-3a19dd4c5fef',
  },
  {
    category: 'Prato Principal',
    name: 'Arroz de Pato',
    description: 'Arroz de forno com pato desfiado e chouriço.',
    origin: 'Portuguesa',
    price: 28,
    id: '3dddc11c-bc67-4a88-9ab2-b3436a7f458c',
  },
  {
    category: 'Prato Principal',
    name: 'Cataplana de Marisco',
    description: 'Guisado de frutos do mar cozido em cataplana.',
    origin: 'Portuguesa',
    price: 40,
    id: 'a6a3bb7f-ecb8-42c6-9cd3-0fce23c1e5b2',
  },
  {
    category: 'Prato Principal',
    name: 'Cozido à Portuguesa',
    description: 'Ensopado de carnes, enchidos e legumes.',
    origin: 'Portuguesa',
    price: 30,
    id: '00c57adb-932b-4dd5-98e3-3de0caa3dbaa',
  },
  {
    category: 'Bebida',
    name: 'Caipirinha',
    description:
      'Tradicional coquetel brasileiro feito com cachaça, limão e açúcar.',
    origin: 'Brasileira',
    price: 10,
    id: 'a2e951ce-b32e-433c-8711-b12a7ea4a69b',
  },
  {
    category: 'Bebida',
    name: 'Batida de Coco',
    description: 'Bebida cremosa de coco com leite condensado e cachaça.',
    origin: 'Brasileira',
    price: 8.5,
    id: '6462a02d-25ac-43f7-ac43-25cffe7d4f2d',
  },
  {
    category: 'Bebida',
    name: 'Suco de Manga',
    description: 'Suco natural de manga, refrescante e saboroso.',
    origin: 'Brasileira',
    price: 7,
    id: '61b21b2a-085b-40f2-8b0c-2e3edbbb497f',
  },
  {
    category: 'Bebida',
    name: 'Guaraná',
    description: 'Refrigerante tradicional brasileiro feito de guaraná.',
    origin: 'Brasileira',
    price: 5,
    id: '19beba62-f60b-458b-abc9-29a8496a574e',
  },
  {
    category: 'Bebida',
    name: 'Limonada Suíça',
    description: 'Limonada feita com limão inteiro, açúcar e água gelada.',
    origin: 'Brasileira',
    price: 6,
    id: '91ee162e-e427-4f55-bb93-bf7e2a1da524',
  },
  {
    category: 'Sobremesa',
    name: 'Pudim de Leite',
    description: 'Delicioso pudim de leite condensado com calda de caramelo.',
    origin: 'Brasileira',
    price: 8,
    id: '084a0c71-ba33-4ff1-a28e-b4beddea6f07',
  },
  {
    category: 'Sobremesa',
    name: 'Brigadeiro',
    description: 'Docinho de chocolate coberto com granulados.',
    origin: 'Brasileira',
    price: 2,
    id: '2589c468-8e3f-4811-9a47-cac8fe30f5e3',
  },
  {
    category: 'Sobremesa',
    name: 'Quindim',
    description: 'Sobremesa de gema de ovo, açúcar e coco.',
    origin: 'Brasileira',
    price: 3,
    id: '2cfc0ef9-acd4-44f3-b0ce-80ac61acb800',
  },
  {
    category: 'Sobremesa',
    name: 'Bolo de Rolo',
    description: 'Bolo fino enrolado com camadas de goiabada.',
    origin: 'Brasileira',
    price: 6,
    id: 'bcb49715-816a-49af-b303-96aa79c7272d',
  },
  {
    category: 'Sobremesa',
    name: 'Beijinho',
    description: 'Docinho de leite condensado com coco ralado.',
    origin: 'Brasileira',
    price: 2,
    id: '52505141-9a70-4a92-8bee-5ce85ad15f2f',
  },
  {
    category: 'Entrada',
    name: 'Sopa de Miso',
    description: 'Sopa tradicional de soja fermentada com tofu e cebolinha.',
    origin: 'Japonesa',
    price: 5,
    id: 'f85fb0df-5b75-4a26-9965-f7450ad3101a',
  },
  {
    category: 'Entrada',
    name: 'Sunomono',
    description: 'Salada de pepino japonês marinado em vinagre doce.',
    origin: 'Japonesa',
    price: 6,
    id: '0efa412c-ac21-4c44-ab6c-9a04d163bf8f',
  },
  {
    category: 'Entrada',
    name: 'Edamame',
    description: 'Vagens de soja cozidas e salpicadas com sal.',
    origin: 'Japonesa',
    price: 4,
    id: 'fd42b19d-6f75-48e4-ba20-207ee314dadd',
  },
  {
    category: 'Entrada',
    name: 'Gyoza',
    description: 'Pasteis japoneses recheados com carne e legumes.',
    origin: 'Japonesa',
    price: 7.5,
    id: 'ef00c7ad-919f-40e3-a8cb-b9d18d2a7d24',
  },
  {
    category: 'Entrada',
    name: 'Tataki de Atum',
    description: 'Atum selado levemente e servido com molho de soja.',
    origin: 'Japonesa',
    price: 12,
    id: '79c150ae-689f-4aaf-a3e6-12743befe595',
  },
  {
    category: 'Prato Principal',
    name: 'Sushi',
    description: 'Peixe cru servido sobre bolinhos de arroz temperado.',
    origin: 'Japonesa',
    price: 18,
    id: 'd77a83c9-af1b-41b2-835c-408bbd04acdc',
  },
  {
    category: 'Prato Principal',
    name: 'Tempurá',
    description: 'Legumes e frutos do mar fritos em massa leve.',
    origin: 'Japonesa',
    price: 15,
    id: '1ff9c57f-4784-4acf-a5d9-fa5304d3d6f4',
  },
  {
    category: 'Prato Principal',
    name: 'Ramen',
    description: 'Sopa de macarrão com caldo rico, carne, ovos e vegetais.',
    origin: 'Japonesa',
    price: 14,
    id: 'ecb91d5f-fd68-4a76-91a6-2423047216a3',
  },
  {
    category: 'Prato Principal',
    name: 'Teriyaki de Frango',
    description: 'Frango grelhado com molho teriyaki doce e salgado.',
    origin: 'Japonesa',
    price: 16,
    id: '7b124070-4373-46f3-bbd4-562d0885ea27',
  },
  {
    category: 'Prato Principal',
    name: 'Okonomiyaki',
    description: 'Panqueca japonesa recheada com diversos ingredientes.',
    origin: 'Japonesa',
    price: 13,
    id: '545a634f-370f-41f0-b55d-89315ba65797',
  },
  {
    category: 'Bebida',
    name: 'Sake',
    description: 'Vinho de arroz tradicional japonês.',
    origin: 'Japonesa',
    price: 8,
    id: 'c519f047-2f9f-474e-892d-139f727e1adc',
  },
  {
    category: 'Bebida',
    name: 'Chá Verde',
    description: 'Chá tradicional feito de folhas de chá verde.',
    origin: 'Japonesa',
    price: 4,
    id: 'faea977c-e2ad-4dfd-a628-7daeac4dc8b2',
  },
  {
    category: 'Bebida',
    name: 'Umeshu',
    description: 'Licor doce feito de ameixa japonesa.',
    origin: 'Japonesa',
    price: 9,
    id: '0c79cc17-66d7-4f11-a7e2-85f85f3bcbf4',
  },
  {
    category: 'Bebida',
    name: 'Ramune',
    description: 'Refrigerante japonês com sabor de limão.',
    origin: 'Japonesa',
    price: 5,
    id: 'eee88fa8-dc47-4321-a7ce-e2f769a6af75',
  },
  {
    category: 'Bebida',
    name: 'Matcha Latte',
    description: 'Bebida cremosa feita com pó de chá verde matcha.',
    origin: 'Japonesa',
    price: 6,
    id: '419ad885-4578-4ad8-96cc-bcb2be6523f7',
  },
  {
    category: 'Sobremesa',
    name: 'Mochi',
    description: 'Bolinhos de arroz glutinoso recheados com pasta doce.',
    origin: 'Japonesa',
    price: 3,
    id: '6582cef6-0509-4520-b0a0-bc5317cc3d55',
  },
  {
    category: 'Sobremesa',
    name: 'Dorayaki',
    description: 'Panquecas japonesas recheadas com pasta de feijão doce.',
    origin: 'Japonesa',
    price: 4,
    id: '85a31fa3-575e-49dc-9aca-23fd8d5c2ee4',
  },
  {
    category: 'Sobremesa',
    name: 'Dango',
    description: 'Bolinhos de arroz glutinoso servidos no espeto.',
    origin: 'Japonesa',
    price: 3.5,
    id: 'e653bc42-ab3c-4b2b-941f-e2caf54712f7',
  },
  {
    category: 'Sobremesa',
    name: 'Taiyaki',
    description: 'Bolinho em forma de peixe recheado com pasta doce.',
    origin: 'Japonesa',
    price: 5,
    id: '74dbb392-6d38-4527-9805-ae1abf094561',
  },
  {
    category: 'Sobremesa',
    name: 'Anmitsu',
    description: 'Sobremesa japonesa com agar-agar, frutas e pasta de feijão.',
    origin: 'Japonesa',
    price: 6.5,
    id: '8b5fb628-f46b-41a7-8a42-28a68c7b4aab',
  },
];
